# Generated by Django 5.0.4 on 2024-05-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quotes",
            name="author",
        ),
        migrations.AddField(
            model_name="quotes",
            name="author",
            field=models.ManyToManyField(to="quotes.author"),
        ),
    ]
