# Generated by Django 5.0.4 on 2024-05-02 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0002_remove_quotes_author_quotes_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quotes",
            name="author",
        ),
        migrations.AddField(
            model_name="quotes",
            name="author",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quotes.author",
            ),
        ),
    ]
